server:
  port: 9000

logging:
  level:
    org.springframework: debug

#
# Spring 配置
spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/default-authorizationserver?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
